title: "Alt-text-ipedia"
description: aims to be a reasonably trustworthy repository of alt text for memes and other frequently shared image content, in the name of accessibility
remote_theme: pmarsceill/just-the-docs